# Critical Manufacturing Framework Continuous Integration Package detection pipeline
# dependsOn:
#             - cmf pipeline

pool:
  name: <%= $CLI_PARAM_AgentPool %>
//#if (agentType == "Cloud")
  vmImage: 'ubuntu-latest'
//#endif

# Trigger on any change in the included branches
trigger:
  branches:
    include:
      - development

# A pipeline with no PR trigger
pr: none

variables:
- template: ../EnvironmentConfigs/GlobalVariables.yml  # Template reference to global variables
- name: GroupName
  value: BuiltHEADs
- name: Pipeline
  value: <%= $CLI_PARAM_PipelinesFolder %>\CI-Builds\CI-Package

workspace:
  clean: all

name: $(Build.SourceBranchName)_$(Build.DefinitionName).$(Build.BuildId)
steps:
- checkout: self
  persistCredentials: true

# install cmf-pipeline
- template: .tasks/install-cmf-pipeline.yml

# find changes and trigger pr-package build
- pwsh: $(CmfPipelinePath)/cmf-pipeline repo findChangedPackages --targetType AzureDevOpsVariableGroup --target $(GroupName) --triggerAzureDevOpsPipeline $(Pipeline)
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: Find changed packages and trigger $(Pipeline)

# Clean Agent Directories
- template: .tasks/clean-agent-directories.yml