# Critical Manufacturing Framework Continuous Integration Package Pipeline
# dependsOn:
#             - cmf cli
#             - cmf pipeline

pool:
  name: <%= $CLI_PARAM_AgentPool %>
//#if (agentType == "Cloud")
  vmImage: 'ubuntu-latest'
//#endif

# A pipeline with no CI trigger
trigger: none

# A pipeline with no PR trigger
pr: none

parameters:
- name: packages
  type: object

variables:
 - template: .vars/global.yml  # Template reference to global variables
 - name: GroupName
   value: BuiltHEADs
 - name: packOutputDir
//#if (agentType == "Cloud")
   value: $(Build.ArtifactStagingDirectory)
//#else
   value: $(CIPackages)/$(Build.SourceBranchName)
//#endif

workspace:
  clean: all

name: $(Build.SourceBranchName)_$(Build.DefinitionName).$(Build.BuildId)
steps:
- checkout: self

# set dotnet version
- template: .tasks/use-dotnet-version.yml

# install cmf-cli
- template: .tasks/install-cli.yml

# install cmf-pipeline
- template: .tasks/install-cmf-pipeline.yml

- ${{ each package in parameters.packages }}:
  # cmf build
  - pwsh: $(CmfCliPath)/cmf build --test
    workingDirectory: ${{ package.path }}
    displayName: Build ${{ package.packageId }} @ ${{ package.path }}

  # cmf pack
  - pwsh: $(CmfCliPath)/cmf pack --force --outputDir $(packOutputDir)
    workingDirectory: ${{ package.path }}
    displayName: Pack ${{ package.packageId }} @ ${{ package.path }}

  # set new built HEAD
  - pwsh: $(CmfPipelinePath)/cmf-pipeline azureDevOps variableGroup updateVariable --group $(GroupName) --key ${{ package.packageId }}@$(Build.SourceBranchName) --value ${{ package.head }}
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: Set variable ${{ package.packageId }}@$(Build.SourceBranchName):${{ package.head }} @ $(GroupName)

//#if (agentType == "Cloud")
# Publish Package Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Package Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'Container'
//#endif

# Clean Agent Directories
- template: .tasks/clean-agent-directories.yml