# Critical Manufacturing Framework Pull Request Package Pipeline
# dependsOn:
#             - cmf pipeline
#             - cmf cli

pool:
  name: <%= $CLI_PARAM_AgentPool %>
//#if (agentType == "Cloud")
  vmImage: 'ubuntu-latest'
//#endif

# A pipeline with no CI trigger
trigger: none

# A pipeline with no PR trigger
pr: none

parameters:
- name: packages
  type: object

variables:
 - template: .vars/global.yml  # Template reference to global variables

workspace:
  clean: all

name: $(Build.SourceBranchName)_$(Build.DefinitionName).$(Build.BuildId)
steps:
- checkout: self

# install cmf-pipeline
- template: .tasks/install-cmf-pipeline.yml

- ${{ each package in parameters.packages }}:
  # package existsInRepos
  - pwsh: $(CmfPipelinePath)/cmf-pipeline package existsInRepos --repo $(ApprovedPackages)
    displayName: Check if ${{ package.packageId }}@${{ package.version }} was not released
    workingDirectory: ${{ package.path }}

# install cmf-cli
- template: .tasks/install-cli.yml

# set dotnet version
- template: .tasks/use-dotnet-version.yml

- ${{ each package in parameters.packages }}:
  # cmf build
  - pwsh: $(CmfCliPath)/cmf build --test
    displayName: Build ${{ package.packageId }} @ ${{ package.path }}
    workingDirectory: ${{ package.path }}

# Publish test and coverage results
- template: .tasks/publish-tests.yml
  parameters:
    Path: $(build.sourcesdirectory)

# Clean Agent Directories
- template: .tasks/clean-agent-directories.yml