variables:
  # Environment Config file name exported from DevOpsCenter
  EnvironmentConfigName: '<%= $CLI_PARAM_ReleaseEnvironmentConfig %>'

  # Run Settings
  RunSettings: 'integration.runsettings'

  # Location of release candidate packages being tested in a release
  CandidatePackages: '<%= $CLI_PARAM_RCRepo %>'

  # Root Package to be installed in CD-VM/CD-Containers
  RootPackageIdToInstall: 'Cmf.Custom.Package'

  # MasterData Filter to be used in CD-VM/CD-Containers
  TestMasterDataFilter: '*MasterData*'

//#if (releaseCustomerEnvironment != "") {
  # Customer Environment Name defined in DevOpsCenter
  CustomerEnvironmentName: '<%= $CLI_PARAM_ReleaseCustomerEnvironment %>'
//#endif

//#if (releaseSite != "") {
  # Site
  SiteName: '<%= $CLI_PARAM_ReleaseSite %>'
//#endif

//#if (releaseDeploymentPackage != "") {
  # Deployment Package
  DeploymentPackage:  '<%= $CLI_PARAM_ReleaseDeploymentPackage %>'
//#endif

//#if (releaseLicense != "") {
  # License
  LicenseName: '<%= $CLI_PARAM_ReleaseLicense %>'
//#endif

//#if (releaseDeploymentTarget != "") {
  # Deployment Target
  DeploymentTarget: '<%= $CLI_PARAM_ReleaseDeploymentTarget %>'
//#endif
