//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmf.Common.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CliMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cmf.Common.Cli.CliMessages", typeof(CliMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found on ContentToPack Sources of {0}.{1}.
        /// </summary>
        internal static string ContentToPackNotFound {
            get {
                return ResourceManager.GetString("ContentToPackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Package {0}.{1}....
        /// </summary>
        internal static string GetPackage {
            get {
                return ResourceManager.GetString("GetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to read the manifest file..
        /// </summary>
        internal static string InvalidManifestFile {
            get {
                return ResourceManager.GetString("InvalidManifestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}, Property {1} doesn&apos;t have the expected value: {2}.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Dependency {0}.{1} not found.
        /// </summary>
        internal static string MissingMandatoryDependency {
            get {
                return ResourceManager.GetString("MissingMandatoryDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory option {0}.
        /// </summary>
        internal static string MissingMandatoryOption {
            get {
                return ResourceManager.GetString("MissingMandatoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory properties: {0}.
        /// </summary>
        internal static string MissingMandatoryProperties {
            get {
                return ResourceManager.GetString("MissingMandatoryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory property {0}.
        /// </summary>
        internal static string MissingMandatoryProperty {
            get {
                return ResourceManager.GetString("MissingMandatoryProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory property {0} in file {1}.
        /// </summary>
        internal static string MissingMandatoryPropertyInFile {
            get {
                return ResourceManager.GetString("MissingMandatoryPropertyInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a root package.
        /// </summary>
        internal static string NotARootPackage {
            get {
                return ResourceManager.GetString("NotARootPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0}.{1} has no test packages.
        /// </summary>
        internal static string PackageHasNoTestPackages {
            get {
                return ResourceManager.GetString("PackageHasNoTestPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find package root. Are you in a valid package directory?.
        /// </summary>
        internal static string PackageRootNotFound {
            get {
                return ResourceManager.GetString("PackageRootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some packages were not found: {0}.
        /// </summary>
        internal static string SomePackagesNotFound {
            get {
                return ResourceManager.GetString("SomePackagesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls not supported yet.
        /// </summary>
        internal static string UrlsNotSupported {
            get {
                return ResourceManager.GetString("UrlsNotSupported", resourceCulture);
            }
        }
    }
}
