<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <TargetName>cmf</TargetName>
        <RootNamespace>Cmf.CLI</RootNamespace>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>cmf</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AssemblyName>cmf</AssemblyName>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <DocumentationFile>../docs/cmf/cmf.xml</DocumentationFile>
        <DefaultDocumentationFileNameMode>Name</DefaultDocumentationFileNameMode>
        <DefaultDocumentationNestedTypeVisibility>Namespace</DefaultDocumentationNestedTypeVisibility>
        <DefaultDocumentationGeneratedPages>Namespaces</DefaultDocumentationGeneratedPages>
        <Version>6.0.0-0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DefaultDocumentation" Version="1.2.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.3.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Spectre.Console" Version="0.55.2" />
        <PackageReference Include="System.CommandLine" Version="2.0.7" />
        <PackageReference Include="System.IO.Abstractions" Version="22.1.1" />
        <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="nupkg\**" />
        <EmbeddedResource Remove="nupkg\**" />
        <None Remove="nupkg\**" />
        <EmbeddedResource Update="CliMessages.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>CliMessages.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <Compile Update="CliMessages.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>CliMessages.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="CliMessages.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>CliMessages.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Include="resources\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="resources\template_feed\**" />
        <Compile Remove="resources\template_feed\**" />
        <None Include="resources\template_feed\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="resources\vendors\**" />
    <Compile Remove="resources\vendors\**" />
    <None Include="resources\vendors\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

    <ItemGroup>
        <Folder Include="Properties\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\.editorconfig" Link=".editorconfig" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\core\core.csproj" />
    </ItemGroup>
</Project>
