site_name: "@criticalmanufacturing/cli Documentation"
site_url: https://criticalmanufacturing.github.io/cli/
site_author: Critical Manufacturing SA
copyright: 2009-present Critical Manufacturing SA
extra_css:
  - stylesheets/extra.css
docs_dir: src
exclude_docs: |
  !/.nojekyll
theme:
  name: material
  logo: assets/cmf-logo.png
  favicon: assets/favicon.ico
  font:
    text: Open Sans
    code: Source Code Pro
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.select
    - content.code.copy
repo_url: https://github.com/criticalmanufacturing/cli
repo_name: criticalmanufacturing/cli
edit_uri: edit/development/docs/src
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
