#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep -E '^(cmf-cli|core)/' >/dev/null; then
    dotnet test --filter "(TestCategory!=LongRunning)&(TestCategory!=Node12)"
fi
