# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: cmf-cli

on:
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'Main tag to publish'
  release:
    types: [published]
jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: install zip
        uses: montudor/action-zip@v0.1.0
      - run: npm install
      - run: npm run build:prod
      - name: create artifact win-x64
        run: zip -X -r ../cmf-cli.win-x64.zip .
        working-directory: dist/win-x64
      - name: Create artifact linux-x64
        run: zip -X -r ../cmf-cli.linux-x64.zip .
        working-directory: dist/linux-x64
      - name: Create artifact osx-x64
        run: zip -X -r ../cmf-cli.osx-x64.zip .
        working-directory: dist/osx-x64
      - name: Publish win-x64 to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/cmf-cli.win-x64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish linux-x64 to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/cmf-cli.linux-x64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish osx-x64 to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/cmf-cli.osx-x64.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run publish
        if: "github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run publish:live
        if: "!github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}